Update bigquery-setup.md with cloud-platform oauth scope
The https://www.googleapis.com/auth/cloud-platform scope is required.

ERROR: (gcloud.auth.application-default.login) Invalid value for [--scopes]: https://www.googleapis.com/auth/cloud-platform scope is required but not requested. Please include it in the --scopes flag.